# Generated by Django 5.2.12 on 2026-03-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_stamped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='signature',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='x_position',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='signature',
            name='y_position',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending_elder', 'Pending Elder Review'), ('pending_pastor', 'Pending Pastor Review'), ('returned_to_clerk', 'Returned to Clerk'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finalized', 'Finalized')], default='pending_elder', max_length=50),
        ),
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api.document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clerk', 'Clerk'), ('elder', 'Elder'), ('pastor', 'Pastor'), ('admin', 'System Administrator')], default='clerk', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together={('document', 'role')},
        ),
    ]
