# Generated by Django 5.2.12 on 2026-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_document_hash_servicerequest_is_stamped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='current_holder',
            field=models.CharField(default='Clerk', max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='current_stage',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VERIFIED', 'Clerk Verified'), ('ELDER_PENDING', 'Awaiting Elder'), ('ELDER_SIGNED', 'Elder Signed'), ('PASTOR_PENDING', 'Awaiting Pastor'), ('FINALIZED', 'Finalized'), ('SENT', 'Sent via WhatsApp')], default='UPLOADED', max_length=50),
        ),
    ]
