# Generated by Django 5.2.12 on 2026-03-12 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useractivity_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/converted/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='final_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/finalized/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
