# Generated by Django 5.2.12 on 2026-03-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seed_production_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='service_request',
        ),
        migrations.AddField(
            model_name='user',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='MinistryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_church', models.CharField(max_length=255)),
                ('receiving_location', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('preacher', 'Preacher Invitation'), ('choir', 'Choir/Group Invitation')], max_length=20)),
                ('invited_name', models.CharField(max_length=255)),
                ('invited_church', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('elder_name', models.CharField(max_length=255)),
                ('elder_contact', models.CharField(max_length=50)),
                ('clerk_name', models.CharField(max_length=255)),
                ('clerk_contact', models.CharField(max_length=50)),
                ('pastor_approved', models.BooleanField(default=False)),
                ('elder_signed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='requests/finalized/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to=settings.AUTH_USER_MODEL)),
                ('elder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_elder', to=settings.AUTH_USER_MODEL)),
                ('pastor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_pastor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='signature',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api.ministryrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ministry_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ministryrequest'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.ministryrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.ministryrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together={('request', 'role')},
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reports/')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='document',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='y_position',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
